service: puller

provider:
  name: aws
  runtime: nodejs10.x

functions:
  puller:
    handler: puller.puller
    environment:
      GITHUB_TOKEN: ${ssm:puller-githubToken~true}
      baseRepoOwner: ${ssm:puller-baseRepoOwner}
      repoName: ${ssm:puller-repoName}
      baseRepoBranch: ${ssm:puller-baseRepoBranch}
      headRepoOwner: ${ssm:puller-headRepoOwner}
      headRepoBranch: ${ssm:puller-headRepoBranch}
    events:
      - schedule: rate(1 hour)
